### PR TITLE
rtmp2rtsp support G711U

### PR DESCRIPTION
**Pull request by jaesung9507**

### CODE REVIEW

**Comment by q191201771** [comment]
@ZSC714725 Review and test this, please.

**Comment by ZSC714725** [comment]
> @ZSC714725 Review and test this, please.

- 8000Hz test success，abnormal sound in other sampling rate tests

**Comment by jaesung9507** [comment]
> > @ZSC714725 Review and test this, please.
> 
> * 8000Hz test success，abnormal sound in other sampling rate tests

support sampling rate other than 8000Hz in G.711?

**Comment by ZSC714725** [comment]
> > > @ZSC714725 Review and test this, please.
> > 
> > 
> > 
> > * 8000Hz test success，abnormal sound in other sampling rate tests
> 
> support sampling rate other than 8000Hz in G.711?

You can consider obtaining the sampling rate from metadata, which may improve the compatibility

**Comment by ZSC714725** [comment]
> > > > > @ZSC714725 Review and test this, please.
> > > > 
> > > > 
> > > > 
> > > > * 8000Hz test success，abnormal sound in other sampling rate tests
> > > 
> > > 
> > > support sampling rate other than 8000Hz in G.711?
> > 
> > 
> > You can consider obtaining the sampling rate from metadata, which may improve the compatibility
> 
> Is metadata the DataMessageAmf0 in RTMP?

yes,you can see it, if there is no sampling rate in metadata, the default 8000 can be used
image

**Comment by jaesung9507** [comment]
@ZSC714725 
I didn't test because I don't have a sample.
Please review and test.
Thanks for review.

**Comment by ZSC714725** [comment]
> @ZSC714725 I didn't test because I don't have a sample. Please review and test. Thanks for review.

test success
image
image

**Comment by ZSC714725** [comment]
> @ZSC714725 I didn't test because I don't have a sample. Please review and test. Thanks for review.

sample:
ffmpeg -re -i source.flv -vcodec copy -acodec pcm_mulaw -f mulaw -ac 1 -ar 44100 -f flv "rtmp://127.0.0.1/live/test110"

**Pull request merged**
