### PR TITLE
ci: add arm64 support

### PR DESCRIPTION
**Pull request by wu-wenxiang**

### CODE REVIEW

**Comment by wu-wenxiang** [comment]
I had tested this patch in ARM environment, & it worked normally.

**Comment by q191201771** [comment]
Have you tested that run the linux/amd64 docker image in the ARM environment?

**Comment by wu-wenxiang** [comment]
> Have you tested that run the linux/amd64 docker image in the ARM environment?

Sorry, I can't catch your points.
1. Linux/amd64 docker image only works in X86 environment.
2. This patch make ci workflow generate ARM & x86 image at the same time, then ARM image & X86 image can work in their respect environments.

**Comment by wu-wenxiang** [comment]
How to pass codecov/project? it's strange...

**Comment by q191201771** [comment]
I'm not familiar with docker so I was wondering if Linux/amd64 docker image could also work in the ARM environment.
And by your answer and others' answers from our open-source community, I know it must match.

I'll merge this PR, and don't bother with the check of codeccov.

Thanks.

**Pull request merged**
