### PR TITLE
reduce memory consumption

### PR DESCRIPTION
**Pull request by kuabhish**
This code change helped me a lot when streaming over 30 streams.
Previously the machine's memory usage went to more than 3 GB.
But after this change, it is limited to 300 MB even when streaming 35 streams.

### CODE REVIEW

**Comment by kuabhish** [comment]
@q191201771

**Comment by kuabhish** [comment]
@q191201771

**Comment by q191201771** [comment]
Thanks for the PR.
But I can't see why this happens.
Technically, you are increasing one more allocation and copy without optimization.
What is your input stream, can you record an flv file for me?

**Comment by kuabhish** [comment]
Hey, thanks for responding.

The value of maxNeededLen is very high here.
```
out := make([]byte, maxNeededLen)
```

because I clear the `out` array as the function ends, the memory used is less.
the new array that I am creating is small compared to the  `out`.

regarding the input stream.
I tried this code in production and I was allowing a lot of people to stream.
So, I don't have a particular video.

**Comment by q191201771** [comment]
Ok, I got your point.
Could you log out maxNeededLen and index for me?

**Comment by kuabhish** [comment]
```
maxneeded len --  4114
index --  446
maxneeded len --  4114
index --  949
maxneeded len --  4114
index --  1351
maxneeded len --  4114
index --  423
```

**Comment by q191201771** [comment]
Ok, I will merge this PR, and I will do some modifications later.
Then you can help me test it.

Let me see if we can preallocate less, so we can avoid allocating twice and the copy.

**Comment by kuabhish** [comment]
Awesome sir, sounds great. Thanks a lot.

**Comment by q191201771** [comment]
reduce preallocate, avoid allocating twice and the copy: https://github.com/q191201771/lal/commit/0188225b8bf3d6cd6aec64f5edb345d3124933ad

add a unit test for the chunk divider: https://github.com/q191201771/lal/commit/4f68ac85edae9f3712f98116f5a9d88610cb2439

**Comment by kuabhish** [comment]
With your commit
I m getting this log.
Seems to be working.
```
maxneeded len --  487
index --  481
maxneeded len --  58
index --  52
maxneeded len --  459
index --  453
maxneeded len --  5494
index --  5471
maxneeded len --  403
index --  397
```

**Comment by q191201771** [comment]
Nice. How about the total memory usage of your scenario?

**Comment by kuabhish** [comment]
Hey sir, Sorry for this late response. I still haven't deployed your changes to my environment because I was on leave. 

I faced this issue not everytime. but only few times. it felt like the values in the out array between index and maxneedelen were not being deleted from the heap by the garbage colector.

After I made this change (PR changes) the improvements were drastic
so I think we should use a combination of your preallocation commit and my changes from this PR.

**Comment by q191201771** [comment]
I'd like to watch the result of your scenario first if possible.

After my changes, the values in the out array between index and maxneedelen will be very little and deleted from the heap by the garbage collector soon or later.

**Comment by kuabhish** [comment]
Screenshot 2023-02-01 at 8 29 00 PM

Screenshot 2023-02-01 at 8 29 59 PM

I took this screenshot few days ago.. 
One plot is the memory used and other plot is the number of streams managed by this machine.

yes after your changes they will be so less that delay in delete by garbage collector wont affect much but still if we add your changes and my changes then no chance of memory leak.

**Comment by q191201771** [comment]
ok, there might 4 versions:

1. old version
2. my new version with my changes
3. your version with your changes
4. my + yours

which version is this picture about? How about other versions' pictures?

**Comment by kuabhish** [comment]
Screenshot 2023-02-08 at 5 38 34 PM
This was happening before my code changes sir.
I dont have a good photo coz it happened few weeks ago.

**Comment by kuabhish** [comment]
> ok, there might 4 versions:
> 
> 1. old version
> 2. my new version with my changes
> 3. your version with your changes
> 4. my + yours
> 
> which version is this picture about? How about other versions' pictures?

version 1 is this .. https://github.com/q191201771/lal/pull/253#issuecomment-1422494411
version 3 is https://github.com/q191201771/lal/pull/253#issuecomment-1422478815

version 2 and version 4 I have to deploy.

**Comment by q191201771** [comment]
Got it. many thanks for these test data.
Try to deploy version 2 if possible.
I have faith that version 2 will work fine too.

**Comment by kuabhish** [comment]
Ok sir. I will surely deploy version 2 and version 4. and get back with the results.

**Comment by kuabhish** [comment]
Hi sir,

https://github.com/arut/nginx-rtmp-module 
we also this repo as our streaming server.
There I see a very clean graph of memory usage.
Screenshot 2023-02-13 at 2 39 19 PM


and when I compare it to the graph of memory usage by this repo.

Attaching the photo show performance of version 4.
Screenshot 2023-02-13 at 2 45 46 PM


I see too many zig-zag in the graph.
What else can be done to improve the performance?

**Comment by kuabhish** [comment]
Screenshot 2023-02-16 at 12 31 29 PM

result for case 4. deployed for 7 days.

**Comment by kuabhish** [comment]
Screenshot 2023-02-18 at 11 45 03 AM

sir, still there is some bug in the code. for only like 10-11 streams this started happening.. and I checked via pprof the most of the memory usage was in the same function `message2Chunks`.

**Pull request merged**
